### ISSUE TITLE
No longer compatible with 2024.2

### ISSUE THREAD

**Issue by R-Bower** [jyjor/angular-file-switcher#4]
The plugin is disabled for 2024.2 EAP builds.  However, disabling and re-enabling the plugin makes it work again.  I think the [supported version](https://github.com/jyjor/angular-file-switcher/blob/main/gradle.properties#L10) needs to be updated.

**Comment by jyjor** [comment]
Yes, you're right. I haven't taken the time to update it, yet. I'll try to get this done today.

**Comment by jyjor** [comment]
I updated this repo and submitted the updated version to JetBrains. They say it can take up to two business days, but it is usually done sooner.

**Comment by jyjor** [comment]
Unfortunately, the update was rejected for a reason that I do not understand. I sent them an email asking for clarification. I will not have time to work on this until next week.

**Comment by R-Bower** [comment]
> Unfortunately, the update was rejected for a reason that I do not understand. I sent them an email asking for clarification. I will not have time to work on this until next week.

I think the gradle version is outdated / deprecated.

**Comment by jyjor** [comment]
It was rejected because it is using a recently-marked-as-internal API. I think I have it figured out, however, and will resubmit soon.

**Comment by jyjor** [comment]
The initial verification came back successful, which means there are no more internal APIs. Hopefully it will get approved. I'll merge and mark this as completed if that happens.

**Comment by jyjor** [comment]
The update was approved and released this morning.
